package com.d1zero.currencyexchange.bottom_navigation

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import com.d1zero.currencyexchange.dto.Currency
import com.d1zero.currencyexchange.screens.CurrencyList
import com.d1zero.currencyexchange.screens.Graphic
import com.d1zero.currencyexchange.screens.History

@Composable
fun NavGraph(navHostController: NavHostController) {
    NavHost(navController = navHostController, startDestination = "currency_list") {
        composable("currency_list") {
            CurrencyList(
                modifier = Modifier,
                currencies = listOf(
                    Currency(
                        1,
                        "RUB",
                        true
                    ),
                    Currency(
                        2,
                        "USD",
                        true
                    ),
                    Currency(
                        3,
                        "EUR",
                        true
                    ),
                    Currency(
                        1,
                        "RUB",
                        true
                    ),
                    Currency(
                        2,
                        "USD",
                        true
                    ),
                    Currency(
                        3,
                        "EUR",
                        true
                    ),
                    Currency(
                        1,
                        "RUB",
                        true
                    ),
                    Currency(
                        2,
                        "USD",
                        true
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ), Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                    Currency(
                        1,
                        "RUB",
                        false
                    ),
                    Currency(
                        2,
                        "USD",
                        false
                    ),
                    Currency(
                        3,
                        "EUR",
                        false
                    ),
                )
            )
        }
        composable("history") {
            History()
        }
        composable("graphic") {
            Graphic()
        }
    }
}